// <auto-generated />
using System;
using Cascadus.Model.Models.DBModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cascadus.Model.Migrations
{
    [DbContext(typeof(CascadusDEVContext))]
    partial class CascadusDEVContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cascadus.Model.Models.DBModels.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Izbrisano")
                        .HasColumnType("bit");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("Cascadus.Model.Models.DBModels.KategorijaProizvoda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Izbrisano")
                        .HasColumnType("bit");

                    b.Property<string>("NazivKategorije")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KategorijaProizvoda");
                });

            modelBuilder.Entity("Cascadus.Model.Models.DBModels.KorisnickiRacun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Izbrisano")
                        .HasColumnType("bit");

                    b.Property<string>("KorisnickoIme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lozinka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uloga")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KorisnickiRacun");
                });

            modelBuilder.Entity("Cascadus.Model.Models.DBModels.Kupac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("Izbrisano")
                        .HasColumnType("bit");

                    b.Property<string>("Kontakt")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("KorisnickiRacunId")
                        .HasColumnName("KorisnickiRacunID")
                        .HasColumnType("int");

                    b.Property<string>("KucniBroj")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PostanskiBroj")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("KorisnickiRacunId");

                    b.ToTable("Kupac");
                });

            modelBuilder.Entity("Cascadus.Model.Models.DBModels.PopustKodovi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Izbrisano")
                        .HasColumnType("bit(1)");

                    b.Property<string>("PopustKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PopustUpostocima")
                        .HasColumnName("PopustUPostocima")
                        .HasColumnType("int");

                    b.Property<DateTime>("VrijediDo")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("PopustKodovi");
                });

            modelBuilder.Entity("Cascadus.Model.Models.DBModels.Proizvod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(19, 4)");

                    b.Property<bool>("Izbrisano")
                        .HasColumnType("bit");

                    b.Property<string>("KarakteristikeProizvoda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KategorijaId")
                        .HasColumnName("KategorijaID")
                        .HasColumnType("int");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpisProizvoda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Putanja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KategorijaId");

                    b.ToTable("Proizvod");
                });

            modelBuilder.Entity("Cascadus.Model.Models.DBModels.Racun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApprovalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrojRacuna")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumIzdavanja")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DatumSlanja")
                        .HasColumnType("date");

                    b.Property<string>("Guid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Izbrisano")
                        .HasColumnType("bit");

                    b.Property<string>("KomentarNarudzbe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KupacId")
                        .HasColumnName("KupacID")
                        .HasColumnType("int");

                    b.Property<string>("NacinPlacanja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PracenjePosiljke")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KupacId");

                    b.ToTable("Racun");
                });

            modelBuilder.Entity("Cascadus.Model.Models.DBModels.Stavka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CijenaPoKomadu")
                        .HasColumnType("decimal(19, 4)");

                    b.Property<bool>("Izbrisano")
                        .HasColumnType("bit");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int>("PopustKodId")
                        .HasColumnName("PopustKodID")
                        .HasColumnType("int");

                    b.Property<int>("ProizvodId")
                        .HasColumnName("ProizvodID")
                        .HasColumnType("int");

                    b.Property<int>("RacunId")
                        .HasColumnName("RacunID")
                        .HasColumnType("int");

                    b.Property<decimal>("UkupnaCijena")
                        .HasColumnType("decimal(19, 4)");

                    b.HasKey("Id");

                    b.HasIndex("PopustKodId");

                    b.HasIndex("ProizvodId");

                    b.HasIndex("RacunId");

                    b.ToTable("Stavka");
                });

            modelBuilder.Entity("Cascadus.Model.Models.DBModels.Kupac", b =>
                {
                    b.HasOne("Cascadus.Model.Models.DBModels.KorisnickiRacun", "KorisnickiRacun")
                        .WithMany("Kupac")
                        .HasForeignKey("KorisnickiRacunId")
                        .HasConstraintName("FK__Kupac__Korisnick__398D8EEE");
                });

            modelBuilder.Entity("Cascadus.Model.Models.DBModels.Proizvod", b =>
                {
                    b.HasOne("Cascadus.Model.Models.DBModels.KategorijaProizvoda", "Kategorija")
                        .WithMany("Proizvod")
                        .HasForeignKey("KategorijaId")
                        .HasConstraintName("FK__Proizvod__Katego__412EB0B6")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cascadus.Model.Models.DBModels.Racun", b =>
                {
                    b.HasOne("Cascadus.Model.Models.DBModels.Kupac", "Kupac")
                        .WithMany("Racun")
                        .HasForeignKey("KupacId")
                        .HasConstraintName("FK__Racun__KupacID__3C69FB99")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cascadus.Model.Models.DBModels.Stavka", b =>
                {
                    b.HasOne("Cascadus.Model.Models.DBModels.PopustKodovi", "PopustKod")
                        .WithMany("Stavka")
                        .HasForeignKey("PopustKodId")
                        .HasConstraintName("FK__Stavka__PopustKo__52593CB8")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cascadus.Model.Models.DBModels.Proizvod", "Proizvod")
                        .WithMany("Stavka")
                        .HasForeignKey("ProizvodId")
                        .HasConstraintName("FK__Stavka__Proizvod__44FF419A")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cascadus.Model.Models.DBModels.Racun", "Racun")
                        .WithMany("Stavka")
                        .HasForeignKey("RacunId")
                        .HasConstraintName("FK__Stavka__RacunID__440B1D61")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
